name: CI with Node.js

on:
  push:
    branches: [ main ]

jobs:
  ci_to_main:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: node app.js
